### ISSUE TITLE
Mosquitto container changes ownership of directory on disk

### ISSUE THREAD

**Issue by mthmulders** [EdwinVW/dapr-workshop#14]
I've run into this on my Linux machine, where I'm developing the Java track for this workshop. After starting the Mosquitto container, I noticed that the ownership of the Mosquitto folder would have changed to `1883:1883`.

The Mosquitto container is started with the current directory mounted into the container as `/mosquitto/config/`. As I understand from eclipse/mosquitto/issues/1078, the container will indeed change ownership of `/mosquitto` to `mosquitto:mosquitto` (to be precise, it happens in the [docker-entrypoint.sh](https://github.com/eclipse/mosquitto/blob/master/docker/2.0/docker-entrypoint.sh#L7) script.

I'm not sure if this is actually something that you can observe on Windows (I hardly ever use that operating system) but at least it happens on Linux and probably also on macOS, and I consider it a bit annoying. Would you be accepting a PR that addresses this, e.g. by copying over the configuration files to a temporary directory and then mounting that one into the Mosquitto container?

**Comment by EdwinVW** [comment]
As long as it also still works on a Windows machine, I'm fine with that.
Just to be clear: what's exactly the issue with the folder's ownership changing?

**Comment by mthmulders** [comment]
The ownership of the folder changes to `1883`, which is most likely not the user id of the person doing the workshop. So they have a folder in their home directory that they cannot write to anymore - the only way to change that is to `sudo chown -R ......` it. It's not an irreversible problem, it's just not that clean :-). And people might be surprised (like I was) or even upset that following the workshop brings up this situation.

**Comment by mthmulders** [comment]
⚠️ **This is potentially disastrous!** ⚠️

The other day, I incidentally ran the Windows command on a Linux machine, and I almost destroyed my setup.

The Windows command is `docker run -d -p 1883:1883 -p 9001:9001 -v $pwd/:/mosquitto/config/ --name dtc-mosquitto eclipse-mosquitto` - as `$pwd` is usually an empty string on Linux, it will map the root directory of the machine as `/mosquitto/config/` in the container.

The container then changes ownership of `/mosquitto/config/` to **1883:1883**. On Linux, it will take a while to do this, but it will eventually render the system unusable, as all files are owned by a non-existing user.

@EdwinVW, is there another way to get the current working directory on Windows? On Linux, we can do ``pwd`` or `$(pwd)`. There are probably some differences that I'm not aware of, but they roughly do the same...

**Comment by EdwinVW** [comment]
I'll look into whether there's another way on Windows.

**Comment by EdwinVW** [comment]
We could also add instructions on how to bake the config file into a Docker container (using COPY) and use that for the workshop.

Would that not fix all issues (also the chmod stuff)??

**Comment by mthmulders** [comment]
That's exactly what my line of thought was...:
> Would you be accepting a PR that addresses this, e.g. by copying over the configuration files to a temporary directory and then mounting that one into the Mosquitto container?

So yes, sounds like a brilliant plan to me :-)

**Comment by mthmulders** [comment]
Apologies for not reading carefully enough. But yeah, copying the config into the container rather than mounting it would also work fine.

**Comment by EdwinVW** [comment]
I have a working solution now. I will do a PR in which I update the way Mosquitto is used, and also update the instructions for .NET and Java so they comply with the updated approach.

**Comment by EdwinVW** [comment]
Fix is in PR #31.

@mthmulders Could you please review.

**Comment by EdwinVW** [comment]
I just executed assignment 6 for .NET and everything worked as expected.
