### ISSUE TITLE
Add a bonus objective to combine different languages?

### ISSUE THREAD

**Issue by wmeints** [EdwinVW/dapr-workshop#22]
Not sure if this is a really good idea. 

Since we have the same HTTP contracts everywhere we could ask people to change things up and combine a bit of Java with .NET (and python when that's ready). 

I would add this as a bonus objective as this requires people to know a bit about running apps for different languages.

**Comment by EdwinVW** [comment]
Nice Idea. 

My two cents: I would prefer to keep the focus for the workshop on learning Dapr and not so much on the different languages. People doing the workshop might get confused when mixing the languages. And if they're already familiar with the languages, this bonus objective would probably not add any value for them.

**Comment by wmeints** [comment]
I agree with the learning focus. I learned from doing my own workshop exercises in Python that it's a lot of work following the instructions. And it can be quite confusing to debug different languages.

It's a fun easter egg that we have a matching contract and schema across the services in Java, Python, and C#. Let's keep it that way and allow people to focus on what matters :)
