### ISSUE TITLE
Line endings in mosquitto when working with WSL2

### ISSUE THREAD

**Issue by wmeints** [EdwinVW/dapr-workshop#25]
I'm using WSL2 as the backend for my docker desktop installation. When I boot the mosquitto container it fails because it can't parse the configuration file. After some debugging I found that the line endings are CRLF instead of LF. This causes issues in WSL2.

**Comment by wmeints** [comment]
Just discussed this with Edwin, we can change the line endings in the config file to LF without causing trouble. So I'm going to fix it in my branch that I have open right now.

**Comment by EdwinVW** [comment]
Fixed in PR #31.
