### ISSUE TITLE
Dapr Actor Model 

### ISSUE THREAD

**Issue by geffzhang** [EdwinVW/dapr-workshop#47]
Dapr Traffic Control Demo of Dapr actors

**Comment by EdwinVW** [comment]
Hi @geffzhang. See the [Dapr traffic-control repo](https://github.com/EdwinVW/dapr-traffic-control#run-the-application-with-dapr-actors) for a demo of Dapr actors. Also check out the chapter on Actors in the [Dapr for .NET Developers ebook](https://docs.microsoft.com/en-us/dotnet/architecture/dapr-for-net-developers/actors).
