### ISSUE TITLE
[Java] Suggestion for Assignment #3

### ISSUE THREAD

**Issue by StevenDevelops** [EdwinVW/dapr-workshop#55]
For [this java tutorial, Assignment #3](https://github.com/EdwinVW/dapr-workshop/blob/main/Assignment03/step-by-step-java.md), the tutorial would be easier to follow if the following 2 steps are swapped, as the current order creates an error initially, and then the error gets resolved in a later step, which can be confusing or misleading to someone following the tutorial:

[This step to declare a Spring Bean makes the IDE throw an error](https://github.com/EdwinVW/dapr-workshop/blame/b2bb1f2fe5ad3d9e7957c33569c6cc4bde89629c/Assignment03/step-by-step-java.md#L352)
should be swapped (or come before) [this step to add a constructor to resolve the error](https://github.com/EdwinVW/dapr-workshop/blame/b2bb1f2fe5ad3d9e7957c33569c6cc4bde89629c/Assignment03/step-by-step-java.md#L375)

**Comment by EdwinVW** [comment]
Hi @StevenDevelops. Thanks for your interest in the Dapr workshop.

@mthmulders: can you look into this suggestion?

**Comment by StevenDevelops** [comment]
@mthmulders great, will take a look

**Comment by mthmulders** [comment]
Closed with [25e5acd](https://github.com/EdwinVW/dapr-workshop/commit/25e5acde134ea6b2215a5e2acf4ef216acc752ff).
